[[pages]]
path = "about_me.py"
name = "About Me"
icon = "ğŸ "

[[pages]]
name = "Portfolio"
icon = "ğŸ¨"
is_section = true

[[pages]]
path = "projects.py"
name = "Projects"
icon = "ğŸ“"

[[pages]]
path = "skills_contact.py"
name = "Skills & Contact"
icon = "ğŸ“"
